/* Check the browser port against the Python model.
 *
 * Python writes cases to data/web_check.json; this replays them in JavaScript and requires
 * an exact match - the same 8x8 input, the same Kenyon cells firing, the same verdict.
 *
 * Exactness is reachable only because both sides quantise the drive before ranking. Gain
 * normalisation makes each cell's weights sum to one, so a cell fed only saturated pixels
 * scores exactly 16, and a bold drawing can leave three hundred cells sitting there with
 * the winner boundary inside that group. Left raw, which of them fire is decided by the
 * last bits of a float64 sum, and numpy's BLAS and a sparse row loop do not agree on those.
 *
 * Run:  node web/digits/verify.js
 */

const fs = require("fs");
const path = require("path");

require("./flybrain.js");

const MIN_CODE_OVERLAP = 1.0;

/* The 8x8 is compared to within one float32 ulp rather than bit-for-bit.
 *
 * numpy sums each 4x4 block pairwise; this file sums it in a loop. On fractional coverage the
 * two orders can land one ulp apart - measured at 1.5e-8 on a value of 0.18 - and no ordering
 * of a JavaScript loop reproduces numpy's pairwise tree in general.
 *
 * That difference changes nothing downstream, and the two assertions that would catch it if it
 * ever did are still exact: every Kenyon cell that fires must be the same cell, and every
 * prediction must be the same prediction. Those are checked at zero tolerance below.
 *
 * Until the fixture was generated by 11_check_the_web.py this comparison was bit-for-bit, and
 * passed - because the hand-drawn cases it held happened to produce whole numbers, where
 * summation order cannot matter. */
const FLOAT32_ULP = Math.pow(2, -23);

function sameToOneUlp(left, right) {
  if (left === right) return true;
  const spread = Math.max(Math.abs(left), Math.abs(right)) * FLOAT32_ULP;
  return Math.abs(left - right) <= spread * 1.0001;
}

const root = path.join(__dirname, "..", "..", "data");
const model = JSON.parse(fs.readFileSync(path.join(root, "flybrain_web.json"), "utf8"));
const cases = JSON.parse(fs.readFileSync(path.join(root, "web_check.json"), "utf8"));

let digitMismatch = 0;
let digitNotExact = 0;
let worstDigitGap = 0;
let labelMismatch = 0;
let worstOverlap = 1;
let differingCells = 0;

for (const item of cases) {
  const result = FlyBrain.read(Float64Array.from(item.ink), item.width, item.height, model);

  let exact = true;
  let beyondUlp = false;
  for (let i = 0; i < item.digit.length; i++) {
    if (result.digit[i] !== item.digit[i]) exact = false;
    if (!sameToOneUlp(result.digit[i], item.digit[i])) beyondUlp = true;
    worstDigitGap = Math.max(worstDigitGap, Math.abs(result.digit[i] - item.digit[i]));
  }
  if (!exact) digitNotExact++;
  if (beyondUlp) digitMismatch++;
  if (result.ranked[0] !== item.prediction) labelMismatch++;

  const expected = new Set(item.code);
  let shared = 0;
  for (let i = 0; i < result.code.length; i++) if (result.code[i] && expected.has(i)) shared++;
  worstOverlap = Math.min(worstOverlap, shared / expected.size);
  differingCells += expected.size - shared;
}

console.log(`cases                 : ${cases.length}`);
console.log(`8x8 beyond one ulp    : ${digitMismatch}   (must be 0)`);
console.log(`8x8 not bit-identical : ${digitNotExact}   (allowed; worst gap ${worstDigitGap.toExponential(2)})`);
console.log(`prediction mismatches : ${labelMismatch}   (must be 0)`);
console.log(`worst code overlap    : ${(worstOverlap * 100).toFixed(2)}%   (must be ${MIN_CODE_OVERLAP * 100}%)`);
console.log(`differing cells       : ${differingCells} of ${cases.length * model.k}`);

if (digitMismatch || labelMismatch || worstOverlap < MIN_CODE_OVERLAP) {
  console.log("\nFAIL - the browser port does not agree with Python");
  process.exit(1);
}
console.log("\nOK - same Kenyon cells, same predictions; preprocessing agrees to within one float32 ulp");
